### ISSUE TITLE
api [cmd] -h 命令bug

### ISSUE THREAD

**Issue by Mazhp** [geetemp/gee-cli#1]
再使用 api [cmd] -h 命令时候，输出信息Usage中，api 和cmd之间多了一条横岗，如图所示：
![1](https://user-images.githubusercontent.com/12904977/42811182-7f215860-89ec-11e8-8ac7-677d7b4e01f3.png)

**Comment by unnKoel** [comment]
@Mazhp 哥，你报错项目了，应该报道api-cli，这里是gee-cli

**Comment by Mazhp** [comment]
我把这个关了。
